services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=herraise
      - DB_USER=postgres
      - DB_PASSWORD=MosesAlier2023
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=True

  db:
    image: postgres:14
    volumes:
      - postgres_data_v14:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=herraise
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MosesAlier2023
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d herraise"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_v14:
